### ISSUE TITLE
Do NPM release or tag & use semantic versioning

### ISSUE THREAD

**Issue by tabrindle** [ma-shop/lint-rules#12]
Currently, we install this package as `ma-shop/lint-rules`, which points to the current commit on master. This does not allow for semantic version, and any time something changes in this repo, we could possibly cause builds to fail across every app and site that uses this repo, without tagging a specific commit. 

If we start releasing to NPM or tagging releases, we can upgrade this package when convenient, without causing CI failures.

**Comment by tjbenton** [comment]
We do release the semantic version `yarn add ma-shop/lint-rules#v0.0.6 --dev` would be the most current release. If your build is failing you can switch to `0.0.5` which should make the lint errors go away
